version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

sphinx:
   # Path to the shared conf.py file.
   configuration: doc/conf.py

python:
   install:
      - method: pip
        path: .
        extra_requirements:
           - doc
