version: 2

sphinx:
   # Path to the shared conf.py file.
   configuration: doc/conf.py

python:
   version: 3.10
   install:
      - method: pip
        path: .
        extra_requirements:
           - doc
